### PR TITLE
[Chore #114660529] Chore/test coverage

### PR DESCRIPTION
**Pull request by gngchrs**
This PR includes tests that had not been written. It increases test coverage to 70%.

### CODE REVIEW

**Comment by unicodeveloper** [comment]
I merged it and I discovered test coverage reduced from 37% to 32%, so I had to revert it. What happened?

**Comment by unicodeveloper** [comment]
Your PR reduces test coverage to 32% @andela-cganga 

screen shot 2016-03-01 at 6 58 01 am

**Comment by gngchrs** [comment]
@unicodeveloper I'm not sure why it's like that. This is what is in the Travis Build. Let me inspect. 

snip20160301_1

**Comment by gngchrs** [comment]
@unicodeveloper I think it's cached. You merged, then you reverted. It should take some time to reflect. I've just seen in coveralls
snip20160301_2

**Comment by gngchrs** [comment]
and that `37%` was for a very old branch. The correct coverage for staging was `32%` according to coveralls dashboard. @unicodeveloper

**Comment by unicodeveloper** [comment]
Alright, but I checked your branch & right now your branch readme was just at 32%, Please send in another PR

**Comment by gngchrs** [comment]
That's because the badge only references the `staging` branch, so that when it is merged it displays coverage for staging. 

It seems I can't make a PR for a reverted PR. Creating a new branch from that branch has failed too, says `Nothing to compare`. Do you have an idea how to go about this? @unicodeveloper

**Comment by unicodeveloper** [comment]
Create a new branch off the previous branch, maybe add some little comments to make it a little different from the previous, then submit a PR. @andela-cganga

**Pull request merged**
