### PR TITLE
[Pibbble][#101284906] Feature/project delete

### PR DESCRIPTION
**Pull request by sirolad**

### CODE REVIEW

**Comment by unicodeveloper** [comment]
Why do we have only delete. Your story says you are working on both update and delete

**Comment by sirolad** [comment]
I am still working on the edit feature, the only challenge i have is that, I need to be getting the item which is to be deleted dynamically.

**Comment by unicodeveloper** [comment]
Please, explain in clear terms, I really do not understand what you said above

**Comment by sirolad** [comment]
This issue has be resolved.

**Pull request merged**
