### PR TITLE
[Fixes #111395814] Social media links not displayed if they are empty

### PR DESCRIPTION
**Pull request by gngchrs**

### CODE REVIEW

**Comment by gngchrs** [comment]
I had a feeling view was getting dirty though! Thanks!

**Comment by gngchrs** [comment]
@unicodeveloper I have refactored it.

**Comment by unicodeveloper** [comment]
Your tests are failing.

**Comment by unicodeveloper** [comment]
I need you to edit the commit messages, it's `function` not `funtion` and it's `Implement` not `Impliment`

**Comment by gngchrs** [comment]
@unicodeveloper I have updated

**Pull request merged**
