### PR TITLE
[Feature #111601192] Teams feature for Pibbble

### PR DESCRIPTION
**Pull request by gngchrs**
This PR adds the teams feature for pibbble, which consists of the following.

:one: You can view all teams by clicking on the **Teams** > **All**. A list of all teams is shown, with their top three resent projects
:two: You can create a team by clicking on the **Create Team** button on the top left of the **Teams > All** view.
:three: Give the team a name, then and a billing email address, then select the Payment Plan you want.
:four: You can then invite members to the team by typing in their names, then press the finish button.
:five: You'll be redirected to your teams settings where you can add an avatar and more options about your team.
:six: There's also a team dashboard, accessible by clicking the **Team Name** badge on the top right corner.
:seven: Members of a team can upload team projects.
:eight: Everyone can follow any team, and it would appear in their followings list in their profile.

### CODE REVIEW

**Comment by gngchrs** [comment]
@unicodeveloper The deployment fails with this error `relation "teams" already exists` I'm trying to figure out why.

**Comment by unicodeveloper** [comment]
Just delete the `teams` table that was already there.

**Comment by gngchrs** [comment]
@unicodeveloper I've deleted it and the deployment works. I'll fix some things then tell you when it's ok.

**Comment by unicodeveloper** [comment]
Alright Fantastic!. Good job. :+1:

**Comment by gngchrs** [comment]
@unicodeveloper I've made the necessary changes. The PR is ready for review.

**Comment by unicodeveloper** [comment]
@andela-womokoro Please, review this PR

**Pull request merged**
