### PR TITLE
[Feature #112787239] A user should be able to hire another user.

### PR DESCRIPTION
**Pull request by gngchrs**
When you navigate to a user's profile/dashboard, you can hire them by clicking on the `Hire Me` button and type in a message. This will send an email to the User, based on what you have written.

### CODE REVIEW

**Comment by unicodeveloper** [comment]
Good work. I discovered that when you click send, there is no success or error message that denotes that the mail has been sent or not.

**Comment by gngchrs** [comment]
@unicodeveloper. I was thinking about that. Is it ok, if I display another modal after this one disappears? Because it feels like there are a lot of modals.

**Comment by unicodeveloper** [comment]
@andela-cganga Instead of displaying another modal, you can make a hidden div show up below the form (still in the same modal) that says something like "The user will get a notification shortly.".

Then if there was an error, the color should be red saying someting like "There was an error sending this message. Please try again"

**Comment by gngchrs** [comment]
@unicodeveloper Ok. Thanks.
Will fix the conflicts too.

**Comment by unicodeveloper** [comment]
Awesome :green_apple:

**Comment by gngchrs** [comment]
@unicodeveloper I have added a progress/notification div to show result of user hire request

**Pull request merged**
