### PR TITLE
[Pibbble][#101606772][Create social media login]

### PR DESCRIPTION
**Pull request by andela-oogunjimi**

### CODE REVIEW

**Comment by unicodeveloper** [comment]
Your commit messages are very inconsistent and does not follow the style we outlined for writing commit messages.. Please fix!

**Comment by andela-oogunjimi** [comment]
Prosper,

I have made updates to the commit messages. Thanks.

Kind regards,
Opeyemi Ogunjimi.
_Software Developer | Andela_
(c) +234-703-936-2475 | Andela.com http://andela.com/

**Comment by unicodeveloper** [comment]
@andela-oogunjimi I need you to rebase and fix the conflicts.

**Comment by andela-oogunjimi** [comment]
Okay, I'll rebase and fix the conflicts.

Just so you should know. I've rebased earlier, before the pull request. I
believe we have the conflicts because you merged a branch into the staging
branch today.

On Mon, Nov 16, 2015 at 10:59 AM, Prosper Otemuyiwa <
notifications@github.com> wrote:

> @andela-oogunjimi https://github.com/andela-oogunjimi I need you to
> rebase and fix the conflicts.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andela/pibbble/pull/114#issuecomment-156975718.

## 

_Opeyemi Ogunjimi | Software Developer | Andela_
(c) +234-703-936-2475 | Andela.com http://andela.com/

**Pull request merged**
