### PR TITLE
[Feature #112330177] Make featured Link be a dropdown with timeframes

### PR DESCRIPTION
**Pull request by gngchrs**
The Featured Link is now a dropdown with timeframes: pastweek, pastmonth and pastyear. Clicking any of the timeframes loads projects within that timeframe.

### CODE REVIEW

**Comment by unicodeveloper** [comment]
Please rebase to resolve the merge conflicts

**Comment by gngchrs** [comment]
@unicodeveloper I've fixed the merge conflict.

**Comment by unicodeveloper** [comment]
You need to process the queries to be case insensitive. For example, if i change `pastWeek` or `pastMonth` to `pastweek` or `pastmonth`, it breaks like so, please fix

screen shot 2016-01-26 at 6 28 10 pm

**Comment by gngchrs** [comment]
@unicodeveloper this is if you do it directly in the browser url?

**Comment by gngchrs** [comment]
@unicodeveloper I have made it case insensitive
The error you were getting wasn't even anything to do with the case. I've made it to load the default timeframe which is now, if anything invalid is provided. 'pastyear' was as invalid as 'reuigjehgd' is invalid.

**Comment by unicodeveloper** [comment]
Note: Please watch your spellings.  Commit [#5c2fae2](https://github.com/andela/pibbble/commit/5c2fae2fe9571f3ee506038ce3e17de5a0951917). It should be `insensitive` instead of `insesitive`.

**Comment by unicodeveloper** [comment]
Please rewrite the commit  [#5c2fae2](https://github.com/andela/pibbble/commit/5c2fae2fe9571f3ee506038ce3e17de5a0951917) to correct the grammatical blunder.

**Comment by gngchrs** [comment]
@unicodeveloper done!

**Pull request merged**
