### PR TITLE
[Feature #111395680] Following & Unfollowing users

### PR DESCRIPTION
**Pull request by gngchrs**
@unicodeveloper there are a few issues with this. Everything works fine but I think I have to load the follow/unfollow modals with an ajax request. Currently the modals are being populated with the page load of /{username} or /dashboard, and so, if I unfollow someone from the modal, I have to do a page refresh to see the changes. 

I want to now refactor it to load the modals from ajax calls, which get the followers and populates the modal instead, without a refresh.

Please advice on any better approach.

### CODE REVIEW

**Comment by unicodeveloper** [comment]
What's the status on this @andela-cganga ?

**Comment by gngchrs** [comment]
@unicodeveloper the badges in /{username},  other people profiles is what is left. Trying to figure out how to update them when one if followed. Looks simple but has been bugging me for a while. I will pair with one of the team members @andela-sakande  tomorrow for some help.

**Comment by gngchrs** [comment]
@unicodeveloper The feature works fine now.

**Comment by unicodeveloper** [comment]
When I am not logged in, and I try to view the number of followers a user has, I get a `401 Unauthorized` error @andela-cganga 

screen shot 2016-01-22 at 11 47 12 am

screen shot 2016-01-22 at 11 50 14 am

**Comment by gngchrs** [comment]
@unicodeveloper Fixed it.

**Comment by unicodeveloper** [comment]
Good Job @andela-cganga :+1:

**Pull request merged**
